### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by im-fin** [loneicewolf/ReverseEngineering#1]
this is retarded and gay kys

**Comment by loneicewolf** [comment]
Hi!
thanks! I thought you had an issue, or you had a question about Updates? and this was it??
:thinking: 

Please; I am recommending you this:
if you dislike a certain field/topic, (like, reverse engineering) (this repository is about reverse engineering **if that wasn't clear from the beginning** for you) - then, Do not browse on such sites/repositories. Why would you do that?

And please try to watch your language. If there is something I can improve, provide **constructive feedback** instead of what you are providing now, which is.. **`destructive feedback`**.

Someone might get extremely offended by the words you just used.
I am quite hard to offend though.  But, as said. Watch your language.

Have a good day!
